---
abstract: 'YQL Perl interface for the Y! Query API'
author:
  - 'Ali Anari <ali@anari.me>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Log::Any::Adapter: 0.11
  Log::Dispatch: 0
  Test::More: 0
  Test::Most: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-YQL
requires:
  Carp: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  List::Util: 1.35
  Log::Any: 0.15
  Log::Any::Adapter: 0.11
  Moo: 1.004002
  Try::Tiny: 0
  URI: 0
  URI::QueryParam: 0
version: 0.0003
